name: Post Snek to Twitter

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          pip install pandas selenium

      - name: Run tweet script
        run: python tweet_snek.py

      - name: Upload debug output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: twitter-debug
          path: |
            debug_tweet_page.png
            debug_page.html
