name: Post Snek to Twitter

on:
  schedule:
    - cron: '0 12 * * *' # 12:00 UTC daily
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.6.0

      - name: Set up Python
        uses: actions/setup-python@v4.9.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          pip install pandas selenium

      - name: Run tweet_snek.py
        run: python tweet_snek.py

      - name: Print Chrome version
        run: chromium-browser --version

      - name: Capture screenshot on failure
        if: failure()
        run: |
          mkdir -p screenshots
          import datetime
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          
          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")

          driver = webdriver.Chrome(options=options)
          driver.get("https://twitter.com")
          driver.save_screenshot("screenshots/debug.png")
          driver.quit()
        shell: python

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@actions/upload-artifact@v3.1.3
        with:
          name: debug-screenshots
          path: screenshots
