name: Daily Tweet Sneks

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12pm UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium pandas

      - name: Install Chrome + Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ ! -e /usr/bin/google-chrome ]; then
            sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
          else
            echo "✔️ /usr/bin/google-chrome already exists, skipping symlink"
          fi


      - name: Run script
        run: python tweet_snek.py

      - name: Print Chrome version
        run: chromium-browser --version

      - name: Debug Screenshot
        if: failure()
        run: |
          mkdir -p screenshots
          mv /tmp/chrome* screenshots/ || true
        continue-on-error: true

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-screenshots
          path: screenshots

