name: Post Snek to Twitter

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.6.0

      - name: Set up Python
        uses: actions/setup-python@v4.9.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          pip install pandas selenium

      - name: Run tweet script
        run: python tweet_snek.py

      - name: Upload tweet screenshot
        if: always()
        uses: actions/upload-artifact@actions/upload-artifact@v3.1.3
        with:
          name: tweet-debug
          path: tweet_ready.png
